services:
  ClementCore\Admin\Admin:
    tags: ['wp.hook']

  ClementCore\Api\OnLiveEndpoint:
    tags: [ 'wp.hook' ]

  ClementCore\Hook\:
    resource: '../../src/Hook/*'
    autowire: true
    tags: [ 'wp.hook' ]
